CREATE DATABASE bank;



CREATE TABLE Users (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    FirstName  varchar(30) NOT NULL,
    SecondName  varchar(30) NOT NULL,
    balance decimal,
    TelephonNumber varchar(30) NOT NULL
);


CREATE TABLE Operation{
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    UserId nteger REFERENCES Users,
    OperationId  REFERENCES OperationType,
}


CREATE TABLE OperationType{
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    TypeName  varchar(30) NOT NULL,
}



-- add users 

insert into Users (FirstName, SecondName, TelephonNumber, balance) values ('Павел','Вилков', '+79135575194', 0);

insert into Users (FirstName, SecondName, TelephonNumber, balance) values ('Артем','Ефремов', '+79135575234', 0);




select * from Users

